name: Test Actions
run-name: ${{ github.actor }} is testing
on: [pull_request, push]
jobs:
    Install-Package:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                lfs: true
            - run: pip install .
            - run: python -m unittest
            - run: pip install -r requirements-dev.txt
            - run: python samples/clustering_raining_data_chile.py