name: Test Actions
run-name: ${{ github.actor }} is testing
on: [pull_request, push]
jobs:
    Install-Package:
        runs-on: ubuntu-latest
        steps:
            - run: pip install .
            - run: python samples/clustering_raining_data_chile.py